name: test_everynight
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  script_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Test
        run: go test -C src/